# fly.toml app configuration file generated for chatgm-synapse on 2023-08-31T17:42:24+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chatgm-synapse"
primary_region = "sin"

[build]
  image = "registry.fly.io/chatgm-synapse:latest"

[http_service]
  internal_port = 8008
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
